# z=open("sample.txt","x")
m=open("sample.txt","w")
m.write("name")
m.write("\nage")
m.close()
m=open("sample.txt","a")
m.write("\nplace")
m.close()
m=open("sample.txt","r")
print(m.read())
m.close()
m=open("sample.txt","r")
print(m.read(2))
m.close()
m=open("sample.txt","r")
print(m.readline())
print(m.readline())
m.close()

# n=open("files.txt",'x')
import os

# os.remove("files.txt")
# os.rmdir("files")