# z=open("new text.txt","x")
# z=open("new text.txt","w")
# z.write("location")
# z.write("\nspeed")
# z.close()
# z=open("new text.txt","a")
# z.write("\nvelocity")
# z.write("\nacceleration")
# z.close()
# z=open("new text.txt","r")
# print(z.read())
# z.close()
# z=open("new text.txt","r")
# print(z.read(10))
# z.close()
# z=open("new text.txt","r")
# print(z.readline())
# print(z.readline())
# print(z.readline())
# z.close()

# y=open("file1.txt","x")
# z=open("file2.txt","x")
# y=open("file1.txt","w")
# y.write("good morning")
# y.close()
# y=open("file1.txt","r")
# v=y.read()
# y.close()
# z=open("file2.txt","w")
# z.write(v)
# p=open("file3.txt","x")
# y=open("file1.txt","r")
# v=y.read()
# y.close()
# z=open("file2.txt","r")
# k=z.read()
# z.close()
# p=open("file3.txt","w")
# l=v+k
# p.write(l)

y=open("file1.txt","r")
z=open("file2.txt","w")
z.write(y.read())
z.close()
y.close()

