x=["cricket","football","baseball","rugby","hockey","tennis"]
print(x)
print(type(x))
print(len(x))
print(x[5])
print(x[1:5])
print(x[3:])
print(x[:5])
print(x[-2])
print(x[-5:-3])
print(x[:-3])
print(x[-4:])
for p in x :
    print(p)
print("badminton" not in x)
print("baseball"not in x)
print("rugby" in x)
print("volleyball" in x)
x[0]="basketball"
print(x)
x.append("soccer")
print(x)
x.insert(5,"boxing")
print(x)
z=["chess","carroms"]
x.extend(z)
x.sort()
print(x)
x.sort(reverse=True)
print(x)
m=z.copy()
l=list(x)
k=m+l
print(k)
print(k.count("chess"))
print(k.remove("boxing"))
print(k.pop(1))
del k[3]
print(k)
k.pop()
print(k)
k.clear()
print(k)
