x="python is a programming language"
print(x)
print(type(x))
print(len(x))
print(x[15])
print(x[5:10])
print(x[2:])
print(x[:8])
print(x[-1])
print(x[-8:-2])
print(x[-10:])
print(x[:-1])
for i in x :
    print(i,end=" ")
print()
print("is" in x)
print("what" in x)
print("a" not in x)
print("at" not in x)
print(x.upper())
print(x.lower())
y="  hello world"
print(y)
print(y.strip())
print(x.split(" "))
print(x.replace("python","java"))
print(x.count("a"))
print(x+y)