x=("chess",'CARROMS',"monoply","cluedo")
print(x)
print(len(x))
print(type(x))
print(x[1])
print(x[1:3])
print(x[:3])
print(x[1:])
print(x[-1])
print(x[-3:-1])
print(x[-3:])
print(x[:-2])
for i in x :
    print(i)
print("chess" in x)
print("chess" not in x)
print('cards' in x)
print("cards" not in x)
y=("scotlandyard",)
print(y)
print(type(y))
a=list(x)
print(a)
a[1]="cards"
print(a)
a.append("ludo")
print(a)
a.pop(3)
print(a)
x=tuple(a)
print(x)
print(x.count("cards"))
print(x+y)
print(y*3)
print(x is y)
